Repository hypar-io/Elements, pull requests merged in 2020-04, with the labels that each got.

#290 Added check for zero length line for short segments
  src/Elements/Geometry/Line.cs
Labels: Bug

#293 Add test for #170 and convenience transform methods.
  CHANGELOG.md
  src/Elements/Geometry/Transform.cs
  src/Elements/Model.cs
  test/Elements.Tests/ColumnTest.cs
Labels: Enhancement, In Review

#295 Fix 221
  CHANGELOG.md
  src/Elements/Generate/GeometricElement.g.cs
  src/Elements/Generate/Geometry/Profile.g.cs
  src/Elements/Generate/Material.g.cs
  src/Elements/Validators/Validators.cs
  test/Elements.Tests/ProfileTests.cs
Labels: In Review

#288 Deprecate Polygon.Circle.
  CHANGELOG.md
  src/Elements/Geometry/Arc.cs
  src/Elements/Geometry/Circle.cs
  src/Elements/Geometry/Curve.cs
  src/Elements/Geometry/Polygons.cs
  src/Elements/Geometry/Profile.cs
  src/Elements/Geometry/Profiles/HSSPipeProfile.cs
  src/Elements/Serialization/IFC/IFCExtensions.cs
  test/Elements.Tests/ArcTests.cs
Labels: Enhancement, In Review

#291 Fix #284.
  CHANGELOG.md
  src/Elements/MeshElement.cs
  src/Elements/Serialization/IFC/IFCElementExtensions.cs
  src/Elements/Topography.cs
  test/Elements.Tests/MeshElementTests.cs
Labels: Bug, IFC, In Review

#297 Fix 229
  CHANGELOG.md
  src/Elements/Geometry/Curve.cs
  src/Elements/Serialization/IFC/IFCElementExtensions.cs
  test/Elements.Tests/StructuralFramingTests.cs
Labels: IFC, In Review

#303 Fix #151.
  CHANGELOG.md
  src/Elements/Generate/TypeGenerator.cs
  test/Elements.Tests/TypeGeneratorTests.cs
Labels: Bug, In Review
